export * from './tabs-demo'
export * from './example-tabs-props'
export * from './pdp-tabs'
export * from './pdp-tabs-with-hash'
export * from './scrollable-pdp-tabs'
export * from './equipment-features-view'
