name: 'Setup Node.js'
description: 'Setup Node.js and Package Manager'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.16'
    - name: Setup Pnpm
      run: corepack enable
      shell: bash
    - name: Enable setup-node cache for Pnpm
      uses: actions/setup-node@v4
      with:
        node-version: '18.16'
        cache: 'pnpm'
    - name: Print versions
      run: |
        node -v
        corepack -v
        pnpm -v
      shell: bash
