export { default as SvgGreenArrow } from './green-arrow'
export { default as IconCheckCycle } from './check-cycle'
export { default as IconXCycle } from './x-cycle'
// Not used
// export { default as SvgDeviceCompare } from './device-compare'
// export { default as SvgDeviceCompareLarge } from './device-compare-large'
// export { default as SvgNoiseCompare } from './noise-compare'
// export { default as SvgNoiseCompareLarge } from './noise-compare-large'
// export { default as SvgWasteToGeme } from './waste-to-geme'
// export { default as SvgWasteToGemeLarge } from './waste-to-geme-large'
export { default as SvgOxygenCycleProgress } from './oxygen-cycle-progress'
export { default as SvgOxygen } from './oxygen'
export { default as SvgFoodWaste } from './food-waste'
export { default as SvgWood } from './wood'
export { default as SvgWaterDrop } from './water-drop'
export { default as SvgTemperature } from './temperature'
export { default as SvgMicrobe } from './microbe'
export * as featureIcons from './feature-icons'
export * as usingCompostIcons from './using-compost-icons'
