name: gemebuild-ci

on:
  push:
    paths:
      - 'pnpm-lock.yaml'
      - 'apps/gemebuild/**'
      - 'packages/**'
      - '.github/workflows/gemebuild-ci.yml'
  workflow_dispatch:

jobs:
  storybook-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - run: pnpm i
      - run: cd apps/gemebuild && pnpm run ci:test-storybook
